security:
    encoders:
        App\Entity\User:
            algorithm: auto
    # 👇 Proveedor de la clase Usuario
    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                # 👇 Valor identificador único
                property: username

    role_hierarchy:
        ROLE_EMPLOYEER: ROLE_USER
        ROLE_STUDENT: ROLE_USER
        ROLE_ARTEAN: [ ROLE_EMPLOYER, ROLE_STUDENT ]

    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern:  ^/register
            stateless: true
            anonymous: true

        api:
            pattern:  ^/api/v1
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/role, role: IS_FULLY_AUTHENTICATED }
        - { path: ^/state, role: IS_FULLY_AUTHENTICATED }
        # OFFERS
        - { path: ^/offers, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/p/offers/([0-9]+), role: ROLE_USER }
        - { path: ^/api/v1/offers/load-offer, role: ROLE_USER }
        - { path: ^/api/v1/p/offers/apply, role: ROLE_STUDENT }
        ## delete and update
        - { path: ^/api/v1/offers/([0-9]+), role: ROLE_EMPLOYER }
        ## insert
        - { path: ^/api/v1/offers/offer-upload, role: ROLE_EMPLOYER }
        - { path: ^/api/v1/offers, role: ROLE_EMPLOYER }
        ## offer by id from owner
        - { path: ^/api/v1/p/offers/([0-9]+), role: ROLE_STUDENT }
        # CV
        - { path: ^/api/v1/cv-upload, role: ROLE_STUDENT }
        ## APPLYMENTS
        - { path: ^/api/v1/applyments/update-state, role: ROLE_EMPLOYER }
        - { path: ^/api/v1/applyments/load-cv, role: ROLE_STUDENT }
        - { path: ^/api/v1/applyments/cvs-offer, role: ROLE_EMPLOYER }
        - { path: ^/api/v1/applyments/state, role: ROLE_STUDENT }
        #  ARTEAN
        - { path: ^/api/v1/artean/students-update-state, role: ROLE_ARTEAN }
        - { path: ^/api/v1/artean/students-pending-activation, role: ROLE_ARTEAN }
        - { path: ^/api/v1/artean/employers-pending-activation, role: ROLE_ARTEAN }
        - { path: ^/api/v1/artean/employers-update-state, role: ROLE_ARTEAN }
        - { path: ^/api/v1/artean/search, role: ROLE_ARTEAN }